<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Services\**" />
    <Page Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="Resources\calculator.ico" />
    <None Remove="Resources\Fonts\Montserrat-VariableFont_wght.ttf" />
    <None Remove="Resources\Icons\calculator.ico" />
    <None Remove="Resources\Images\calculator.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\calculator.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\Montserrat-VariableFont_wght.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Icons\calculator.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
